### ISSUE TITLE
conda install ryven

### ISSUE THREAD

**Issue by WillAdams** [jan-janssen/conda-forge-contribution#1]
This isn't working in the Windows 10 using the current Anaconda distribution:

(base) C:\Users\willa>conda config --add channels conda-forge
Warning: 'conda-forge' already in 'channels' list, moving to the top

(base) C:\Users\willa>conda config --set channel_priority strict

(base) C:\Users\willa>conda install ryven
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining @/win-64::__win==0=0:  25%|█████████████                                       | 1/4 [00:00<00:02Examining @/win-64::__win==0=0:  50%|██████████████████████████                          | 2/4Examining @/win-64::__archspec==1=x86_64:  50%|█████████████████████                     | 2/4 [00:Examining ryven:  75%|█████████████████████████████████████████████████failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
Note that strict channel priority may have removed packages required for satisfiability.

(base) C:\Users\willa>

**Comment by jan-janssen** [comment]
Yes, unfortunately the `pyside2` version is not available on Windows https://github.com/leon-thomm/Ryven/issues/90
